### ISSUE TITLE
Why isn't this project part of the Jenkins distribution?

### ISSUE THREAD

**Issue by tgarc** [jenkinsci/sge-cloud-plugin#1]
Why is it that your project isn't listed in Jenkins available plug ins?

**Comment by jmcgeheeiv** [comment]
Distribution of this plugin was suspended due to unresolved security vulnerabilities in the prerequisite [Copy-To-Slave Plugin](https://wiki.jenkins.io/display/JENKINS/Copy+To+Slave+Plugin).

SGE Cloud Plugin [branch `remove-copy-to-slave`](https://github.com/jenkinsci/sge-cloud-plugin/tree/remove-copy-to-slave) contains an incomplete attempt at eliminating the Copy-To-Slave dependency. Please help by completing this enhancement.
